//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPC.SISDUC.Model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectRequestOfOleoductorLr2Zji1", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CNPC.SISDUC.Model.Servicio.OleoductoRequest))]
    public partial class ObjectRequestOfOleoductorLr2Zji1 : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CNPC.SISDUC.Model.Oleoducto ItemField;
        
        private CNPC.SISDUC.Model.Operacion OperacionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.Oleoducto Item
        {
            get
            {
                return this.ItemField;
            }
            set
            {
                this.ItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.Operacion Operacion
        {
            get
            {
                return this.OperacionField;
            }
            set
            {
                this.OperacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Oleoducto", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model")]
    public partial class Oleoducto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> BLPDField;
        
        private string BSWField;
        
        private string ClienteField;
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private System.Nullable<System.DateTime> FechaInspeccionField;
        
        private int IdField;
        
        private System.DateTime LastUpdateField;
        
        private decimal LongitudTotalField;
        
        private string Material1Field;
        
        private string Material2Field;
        
        private string Material3Field;
        
        private string NoLaminaField;
        
        private System.Nullable<decimal> PresionField;
        
        private string RowStateField;
        
        private System.Nullable<int> Schedule1Field;
        
        private System.Nullable<int> Schedule2Field;
        
        private System.Nullable<int> Schedule3Field;
        
        private System.Nullable<decimal> TemperaturaField;
        
        private string UbicacionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BLPD
        {
            get
            {
                return this.BLPDField;
            }
            set
            {
                this.BLPDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BSW
        {
            get
            {
                return this.BSWField;
            }
            set
            {
                this.BSWField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cliente
        {
            get
            {
                return this.ClienteField;
            }
            set
            {
                this.ClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaInspeccion
        {
            get
            {
                return this.FechaInspeccionField;
            }
            set
            {
                this.FechaInspeccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdate
        {
            get
            {
                return this.LastUpdateField;
            }
            set
            {
                this.LastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LongitudTotal
        {
            get
            {
                return this.LongitudTotalField;
            }
            set
            {
                this.LongitudTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Material1
        {
            get
            {
                return this.Material1Field;
            }
            set
            {
                this.Material1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Material2
        {
            get
            {
                return this.Material2Field;
            }
            set
            {
                this.Material2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Material3
        {
            get
            {
                return this.Material3Field;
            }
            set
            {
                this.Material3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoLamina
        {
            get
            {
                return this.NoLaminaField;
            }
            set
            {
                this.NoLaminaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Presion
        {
            get
            {
                return this.PresionField;
            }
            set
            {
                this.PresionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RowState
        {
            get
            {
                return this.RowStateField;
            }
            set
            {
                this.RowStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Schedule1
        {
            get
            {
                return this.Schedule1Field;
            }
            set
            {
                this.Schedule1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Schedule2
        {
            get
            {
                return this.Schedule2Field;
            }
            set
            {
                this.Schedule2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Schedule3
        {
            get
            {
                return this.Schedule3Field;
            }
            set
            {
                this.Schedule3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Temperatura
        {
            get
            {
                return this.TemperaturaField;
            }
            set
            {
                this.TemperaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubicacion
        {
            get
            {
                return this.UbicacionField;
            }
            set
            {
                this.UbicacionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operacion", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model")]
    public enum Operacion : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Agregar = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Actualizar = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Eliminar = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BuscarPorId = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfOleoductorLr2Zji1", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CNPC.SISDUC.Model.Servicio.OleoductoResponse))]
    public partial class ResponseOfOleoductorLr2Zji1 : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CNPC.SISDUC.Model.Oleoducto ItemField;
        
        private CNPC.SISDUC.Model.Oleoducto[] ListField;
        
        private int PageField;
        
        private int RecordsField;
        
        private int TotalPagesField;
        
        private int TotalRecordsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.Oleoducto Item
        {
            get
            {
                return this.ItemField;
            }
            set
            {
                this.ItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.Oleoducto[] List
        {
            get
            {
                return this.ListField;
            }
            set
            {
                this.ListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page
        {
            get
            {
                return this.PageField;
            }
            set
            {
                this.PageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Records
        {
            get
            {
                return this.RecordsField;
            }
            set
            {
                this.RecordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages
        {
            get
            {
                return this.TotalPagesField;
            }
            set
            {
                this.TotalPagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords
        {
            get
            {
                return this.TotalRecordsField;
            }
            set
            {
                this.TotalRecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectRequestOfRegistroInspeccionVisualrLr2Zji1", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualRequest))]
    public partial class ObjectRequestOfRegistroInspeccionVisualrLr2Zji1 : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CNPC.SISDUC.Model.RegistroInspeccionVisual ItemField;
        
        private CNPC.SISDUC.Model.Operacion OperacionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.RegistroInspeccionVisual Item
        {
            get
            {
                return this.ItemField;
            }
            set
            {
                this.ItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.Operacion Operacion
        {
            get
            {
                return this.OperacionField;
            }
            set
            {
                this.OperacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistroInspeccionVisual", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model")]
    public partial class RegistroInspeccionVisual : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<decimal> BSCANField;
        
        private string CodigoField;
        
        private string CodigoDelTuboField;
        
        private string CodigoDelTubo02Field;
        
        private string CodigoDelTubo03Field;
        
        private string CondicionDelTramoField;
        
        private string CoordenadasUTM_XField;
        
        private string CoordenadasUTM_YField;
        
        private System.Nullable<bool> CruceCarreteraField;
        
        private string DefectoField;
        
        private string Defecto2Field;
        
        private System.Nullable<bool> ElastomeroField;
        
        private System.Nullable<decimal> EspesorMinimoRealRemanenteField;
        
        private System.Nullable<decimal> EspesorNominalField;
        
        private System.Nullable<decimal> EspesorParedField;
        
        private System.Nullable<decimal> EspesorRemanenteField;
        
        private string EstadoProteccionField;
        
        private string EstadoTuberiaField;
        
        private System.Nullable<decimal> ExtremoFinal1Field;
        
        private System.Nullable<decimal> ExtremoFinal2Field;
        
        private System.Nullable<decimal> ExtremoFinal3Field;
        
        private System.Nullable<decimal> ExtremoFinal4Field;
        
        private System.Nullable<decimal> ExtremoInicial1Field;
        
        private System.Nullable<decimal> ExtremoInicial2Field;
        
        private System.Nullable<decimal> ExtremoInicial3Field;
        
        private System.Nullable<decimal> ExtremoInicial4Field;
        
        private System.Nullable<decimal> ExtremoMedio1Field;
        
        private System.Nullable<decimal> ExtremoMedio2Field;
        
        private System.Nullable<decimal> ExtremoMedio3Field;
        
        private System.Nullable<decimal> ExtremoMedio4Field;
        
        private int IdField;
        
        private System.Nullable<decimal> LEFT_MINIMOField;
        
        private System.Nullable<System.DateTime> LastUpdateField;
        
        private System.Nullable<decimal> LongitudField;
        
        private System.Nullable<bool> MalezaField;
        
        private System.Nullable<decimal> MapeoCorrisonField;
        
        private System.Nullable<int> NPSField;
        
        private System.Nullable<int> NumeroAnteriorField;
        
        private System.Nullable<int> NumeroGrapasField;
        
        private string NumeroOleoductoField;
        
        private string ObservacionesDeLaInspeccionVisualField;
        
        private int OleoductoIDField;
        
        private System.Nullable<bool> PinturaField;
        
        private System.Nullable<decimal> PitCorrosionField;
        
        private string RowStateField;
        
        private System.Nullable<int> SHCField;
        
        private System.Nullable<int> ScheduleField;
        
        private System.Nullable<bool> SeleccionarTuberiaField;
        
        private string TipoMaterialField;
        
        private string TipoProteccionField;
        
        private string TipoSoporteField;
        
        private System.Nullable<bool> TuberiaAlrededorField;
        
        private System.Nullable<System.DateTime> UltimaFechaDeInspeccionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BSCAN
        {
            get
            {
                return this.BSCANField;
            }
            set
            {
                this.BSCANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDelTubo
        {
            get
            {
                return this.CodigoDelTuboField;
            }
            set
            {
                this.CodigoDelTuboField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDelTubo02
        {
            get
            {
                return this.CodigoDelTubo02Field;
            }
            set
            {
                this.CodigoDelTubo02Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDelTubo03
        {
            get
            {
                return this.CodigoDelTubo03Field;
            }
            set
            {
                this.CodigoDelTubo03Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CondicionDelTramo
        {
            get
            {
                return this.CondicionDelTramoField;
            }
            set
            {
                this.CondicionDelTramoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoordenadasUTM_X
        {
            get
            {
                return this.CoordenadasUTM_XField;
            }
            set
            {
                this.CoordenadasUTM_XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoordenadasUTM_Y
        {
            get
            {
                return this.CoordenadasUTM_YField;
            }
            set
            {
                this.CoordenadasUTM_YField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CruceCarretera
        {
            get
            {
                return this.CruceCarreteraField;
            }
            set
            {
                this.CruceCarreteraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Defecto
        {
            get
            {
                return this.DefectoField;
            }
            set
            {
                this.DefectoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Defecto2
        {
            get
            {
                return this.Defecto2Field;
            }
            set
            {
                this.Defecto2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Elastomero
        {
            get
            {
                return this.ElastomeroField;
            }
            set
            {
                this.ElastomeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> EspesorMinimoRealRemanente
        {
            get
            {
                return this.EspesorMinimoRealRemanenteField;
            }
            set
            {
                this.EspesorMinimoRealRemanenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> EspesorNominal
        {
            get
            {
                return this.EspesorNominalField;
            }
            set
            {
                this.EspesorNominalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> EspesorPared
        {
            get
            {
                return this.EspesorParedField;
            }
            set
            {
                this.EspesorParedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> EspesorRemanente
        {
            get
            {
                return this.EspesorRemanenteField;
            }
            set
            {
                this.EspesorRemanenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoProteccion
        {
            get
            {
                return this.EstadoProteccionField;
            }
            set
            {
                this.EstadoProteccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoTuberia
        {
            get
            {
                return this.EstadoTuberiaField;
            }
            set
            {
                this.EstadoTuberiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExtremoFinal1
        {
            get
            {
                return this.ExtremoFinal1Field;
            }
            set
            {
                this.ExtremoFinal1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExtremoFinal2
        {
            get
            {
                return this.ExtremoFinal2Field;
            }
            set
            {
                this.ExtremoFinal2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExtremoFinal3
        {
            get
            {
                return this.ExtremoFinal3Field;
            }
            set
            {
                this.ExtremoFinal3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExtremoFinal4
        {
            get
            {
                return this.ExtremoFinal4Field;
            }
            set
            {
                this.ExtremoFinal4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExtremoInicial1
        {
            get
            {
                return this.ExtremoInicial1Field;
            }
            set
            {
                this.ExtremoInicial1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExtremoInicial2
        {
            get
            {
                return this.ExtremoInicial2Field;
            }
            set
            {
                this.ExtremoInicial2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExtremoInicial3
        {
            get
            {
                return this.ExtremoInicial3Field;
            }
            set
            {
                this.ExtremoInicial3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExtremoInicial4
        {
            get
            {
                return this.ExtremoInicial4Field;
            }
            set
            {
                this.ExtremoInicial4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExtremoMedio1
        {
            get
            {
                return this.ExtremoMedio1Field;
            }
            set
            {
                this.ExtremoMedio1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExtremoMedio2
        {
            get
            {
                return this.ExtremoMedio2Field;
            }
            set
            {
                this.ExtremoMedio2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExtremoMedio3
        {
            get
            {
                return this.ExtremoMedio3Field;
            }
            set
            {
                this.ExtremoMedio3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExtremoMedio4
        {
            get
            {
                return this.ExtremoMedio4Field;
            }
            set
            {
                this.ExtremoMedio4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LEFT_MINIMO
        {
            get
            {
                return this.LEFT_MINIMOField;
            }
            set
            {
                this.LEFT_MINIMOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastUpdate
        {
            get
            {
                return this.LastUpdateField;
            }
            set
            {
                this.LastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Longitud
        {
            get
            {
                return this.LongitudField;
            }
            set
            {
                this.LongitudField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Maleza
        {
            get
            {
                return this.MalezaField;
            }
            set
            {
                this.MalezaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MapeoCorrison
        {
            get
            {
                return this.MapeoCorrisonField;
            }
            set
            {
                this.MapeoCorrisonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NPS
        {
            get
            {
                return this.NPSField;
            }
            set
            {
                this.NPSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroAnterior
        {
            get
            {
                return this.NumeroAnteriorField;
            }
            set
            {
                this.NumeroAnteriorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroGrapas
        {
            get
            {
                return this.NumeroGrapasField;
            }
            set
            {
                this.NumeroGrapasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroOleoducto
        {
            get
            {
                return this.NumeroOleoductoField;
            }
            set
            {
                this.NumeroOleoductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacionesDeLaInspeccionVisual
        {
            get
            {
                return this.ObservacionesDeLaInspeccionVisualField;
            }
            set
            {
                this.ObservacionesDeLaInspeccionVisualField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OleoductoID
        {
            get
            {
                return this.OleoductoIDField;
            }
            set
            {
                this.OleoductoIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Pintura
        {
            get
            {
                return this.PinturaField;
            }
            set
            {
                this.PinturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PitCorrosion
        {
            get
            {
                return this.PitCorrosionField;
            }
            set
            {
                this.PitCorrosionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RowState
        {
            get
            {
                return this.RowStateField;
            }
            set
            {
                this.RowStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SHC
        {
            get
            {
                return this.SHCField;
            }
            set
            {
                this.SHCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Schedule
        {
            get
            {
                return this.ScheduleField;
            }
            set
            {
                this.ScheduleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SeleccionarTuberia
        {
            get
            {
                return this.SeleccionarTuberiaField;
            }
            set
            {
                this.SeleccionarTuberiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoMaterial
        {
            get
            {
                return this.TipoMaterialField;
            }
            set
            {
                this.TipoMaterialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoProteccion
        {
            get
            {
                return this.TipoProteccionField;
            }
            set
            {
                this.TipoProteccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoSoporte
        {
            get
            {
                return this.TipoSoporteField;
            }
            set
            {
                this.TipoSoporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> TuberiaAlrededor
        {
            get
            {
                return this.TuberiaAlrededorField;
            }
            set
            {
                this.TuberiaAlrededorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UltimaFechaDeInspeccion
        {
            get
            {
                return this.UltimaFechaDeInspeccionField;
            }
            set
            {
                this.UltimaFechaDeInspeccionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfRegistroInspeccionVisualrLr2Zji1", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualResponse))]
    public partial class ResponseOfRegistroInspeccionVisualrLr2Zji1 : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CNPC.SISDUC.Model.RegistroInspeccionVisual ItemField;
        
        private CNPC.SISDUC.Model.RegistroInspeccionVisual[] ListField;
        
        private int PageField;
        
        private int RecordsField;
        
        private int TotalPagesField;
        
        private int TotalRecordsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.RegistroInspeccionVisual Item
        {
            get
            {
                return this.ItemField;
            }
            set
            {
                this.ItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.RegistroInspeccionVisual[] List
        {
            get
            {
                return this.ListField;
            }
            set
            {
                this.ListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page
        {
            get
            {
                return this.PageField;
            }
            set
            {
                this.PageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Records
        {
            get
            {
                return this.RecordsField;
            }
            set
            {
                this.RecordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages
        {
            get
            {
                return this.TotalPagesField;
            }
            set
            {
                this.TotalPagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords
        {
            get
            {
                return this.TotalRecordsField;
            }
            set
            {
                this.TotalRecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectRequestOfAccesoriorLr2Zji1", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CNPC.SISDUC.Model.Servicio.AccesoriosRequest))]
    public partial class ObjectRequestOfAccesoriorLr2Zji1 : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CNPC.SISDUC.Model.Accesorio ItemField;
        
        private CNPC.SISDUC.Model.Operacion OperacionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.Accesorio Item
        {
            get
            {
                return this.ItemField;
            }
            set
            {
                this.ItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.Operacion Operacion
        {
            get
            {
                return this.OperacionField;
            }
            set
            {
                this.OperacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Accesorio", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model")]
    public partial class Accesorio : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Accesorio1Field;
        
        private System.Nullable<decimal> BSCANField;
        
        private string CodigoAccesorio1Field;
        
        private string CodigoAccesorio2Field;
        
        private string CodigoAccesorio3Field;
        
        private System.Nullable<int> CoordenadasUTMXField;
        
        private System.Nullable<int> CoordenadasUTMYField;
        
        private string Defecto1Field;
        
        private string Defecto2Field;
        
        private System.Nullable<decimal> EspesorParedField;
        
        private System.Nullable<decimal> EspesorRemanenteField;
        
        private string EstadoAccesorioField;
        
        private System.Nullable<decimal> ExtremoFinalField;
        
        private System.Nullable<decimal> ExtremoInicialField;
        
        private System.Nullable<decimal> ExtremoMedioField;
        
        private int IdField;
        
        private System.Nullable<decimal> InspeccionSonicaField;
        
        private System.Nullable<System.DateTime> LastUpdateField;
        
        private System.Nullable<decimal> LongitudField;
        
        private System.Nullable<decimal> MapeoCorrosionField;
        
        private System.Nullable<int> NPSField;
        
        private System.Nullable<int> NumeroGrapasField;
        
        private string ObservacionesField;
        
        private System.Nullable<bool> PinturaField;
        
        private System.Nullable<decimal> PitCorrosionField;
        
        private string RowStateField;
        
        private System.Nullable<int> ScheduleField;
        
        private string TipoAccesorioField;
        
        private string TipoMaterialField;
        
        private System.Nullable<int> TuberiaIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Accesorio1
        {
            get
            {
                return this.Accesorio1Field;
            }
            set
            {
                this.Accesorio1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BSCAN
        {
            get
            {
                return this.BSCANField;
            }
            set
            {
                this.BSCANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAccesorio1
        {
            get
            {
                return this.CodigoAccesorio1Field;
            }
            set
            {
                this.CodigoAccesorio1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAccesorio2
        {
            get
            {
                return this.CodigoAccesorio2Field;
            }
            set
            {
                this.CodigoAccesorio2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAccesorio3
        {
            get
            {
                return this.CodigoAccesorio3Field;
            }
            set
            {
                this.CodigoAccesorio3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CoordenadasUTMX
        {
            get
            {
                return this.CoordenadasUTMXField;
            }
            set
            {
                this.CoordenadasUTMXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CoordenadasUTMY
        {
            get
            {
                return this.CoordenadasUTMYField;
            }
            set
            {
                this.CoordenadasUTMYField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Defecto1
        {
            get
            {
                return this.Defecto1Field;
            }
            set
            {
                this.Defecto1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Defecto2
        {
            get
            {
                return this.Defecto2Field;
            }
            set
            {
                this.Defecto2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> EspesorPared
        {
            get
            {
                return this.EspesorParedField;
            }
            set
            {
                this.EspesorParedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> EspesorRemanente
        {
            get
            {
                return this.EspesorRemanenteField;
            }
            set
            {
                this.EspesorRemanenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoAccesorio
        {
            get
            {
                return this.EstadoAccesorioField;
            }
            set
            {
                this.EstadoAccesorioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExtremoFinal
        {
            get
            {
                return this.ExtremoFinalField;
            }
            set
            {
                this.ExtremoFinalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExtremoInicial
        {
            get
            {
                return this.ExtremoInicialField;
            }
            set
            {
                this.ExtremoInicialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExtremoMedio
        {
            get
            {
                return this.ExtremoMedioField;
            }
            set
            {
                this.ExtremoMedioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> InspeccionSonica
        {
            get
            {
                return this.InspeccionSonicaField;
            }
            set
            {
                this.InspeccionSonicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastUpdate
        {
            get
            {
                return this.LastUpdateField;
            }
            set
            {
                this.LastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Longitud
        {
            get
            {
                return this.LongitudField;
            }
            set
            {
                this.LongitudField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MapeoCorrosion
        {
            get
            {
                return this.MapeoCorrosionField;
            }
            set
            {
                this.MapeoCorrosionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NPS
        {
            get
            {
                return this.NPSField;
            }
            set
            {
                this.NPSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroGrapas
        {
            get
            {
                return this.NumeroGrapasField;
            }
            set
            {
                this.NumeroGrapasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones
        {
            get
            {
                return this.ObservacionesField;
            }
            set
            {
                this.ObservacionesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Pintura
        {
            get
            {
                return this.PinturaField;
            }
            set
            {
                this.PinturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PitCorrosion
        {
            get
            {
                return this.PitCorrosionField;
            }
            set
            {
                this.PitCorrosionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RowState
        {
            get
            {
                return this.RowStateField;
            }
            set
            {
                this.RowStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Schedule
        {
            get
            {
                return this.ScheduleField;
            }
            set
            {
                this.ScheduleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoAccesorio
        {
            get
            {
                return this.TipoAccesorioField;
            }
            set
            {
                this.TipoAccesorioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoMaterial
        {
            get
            {
                return this.TipoMaterialField;
            }
            set
            {
                this.TipoMaterialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TuberiaId
        {
            get
            {
                return this.TuberiaIdField;
            }
            set
            {
                this.TuberiaIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfAccesoriorLr2Zji1", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CNPC.SISDUC.Model.Servicio.AccesorioResponse))]
    public partial class ResponseOfAccesoriorLr2Zji1 : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CNPC.SISDUC.Model.Accesorio ItemField;
        
        private CNPC.SISDUC.Model.Accesorio[] ListField;
        
        private int PageField;
        
        private int RecordsField;
        
        private int TotalPagesField;
        
        private int TotalRecordsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.Accesorio Item
        {
            get
            {
                return this.ItemField;
            }
            set
            {
                this.ItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.Accesorio[] List
        {
            get
            {
                return this.ListField;
            }
            set
            {
                this.ListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page
        {
            get
            {
                return this.PageField;
            }
            set
            {
                this.PageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Records
        {
            get
            {
                return this.RecordsField;
            }
            set
            {
                this.RecordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages
        {
            get
            {
                return this.TotalPagesField;
            }
            set
            {
                this.TotalPagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords
        {
            get
            {
                return this.TotalRecordsField;
            }
            set
            {
                this.TotalRecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectRequestOfUsuariorLr2Zji1", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CNPC.SISDUC.Model.Servicio.UsuarioRequest))]
    public partial class ObjectRequestOfUsuariorLr2Zji1 : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CNPC.SISDUC.Model.Usuario ItemField;
        
        private CNPC.SISDUC.Model.Operacion OperacionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.Usuario Item
        {
            get
            {
                return this.ItemField;
            }
            set
            {
                this.ItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.Operacion Operacion
        {
            get
            {
                return this.OperacionField;
            }
            set
            {
                this.OperacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model")]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ActiveDirectoryField;
        
        private bool ActivoField;
        
        private string ApellidoField;
        
        private string ContraseniaField;
        
        private int FacilitadorIdField;
        
        private int FiscalizadorIdField;
        
        private int IdField;
        
        private System.DateTime LastUpdateField;
        
        private string NombreField;
        
        private int RolIdField;
        
        private string RowStateField;
        
        private string Usuario1Field;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ActiveDirectory
        {
            get
            {
                return this.ActiveDirectoryField;
            }
            set
            {
                this.ActiveDirectoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo
        {
            get
            {
                return this.ActivoField;
            }
            set
            {
                this.ActivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido
        {
            get
            {
                return this.ApellidoField;
            }
            set
            {
                this.ApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia
        {
            get
            {
                return this.ContraseniaField;
            }
            set
            {
                this.ContraseniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FacilitadorId
        {
            get
            {
                return this.FacilitadorIdField;
            }
            set
            {
                this.FacilitadorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FiscalizadorId
        {
            get
            {
                return this.FiscalizadorIdField;
            }
            set
            {
                this.FiscalizadorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdate
        {
            get
            {
                return this.LastUpdateField;
            }
            set
            {
                this.LastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RolId
        {
            get
            {
                return this.RolIdField;
            }
            set
            {
                this.RolIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RowState
        {
            get
            {
                return this.RowStateField;
            }
            set
            {
                this.RowStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario1
        {
            get
            {
                return this.Usuario1Field;
            }
            set
            {
                this.Usuario1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfUsuariorLr2Zji1", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CNPC.SISDUC.Model.Servicio.UsuarioResponse))]
    public partial class ResponseOfUsuariorLr2Zji1 : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CNPC.SISDUC.Model.Usuario ItemField;
        
        private CNPC.SISDUC.Model.Usuario[] ListField;
        
        private int PageField;
        
        private int RecordsField;
        
        private int TotalPagesField;
        
        private int TotalRecordsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.Usuario Item
        {
            get
            {
                return this.ItemField;
            }
            set
            {
                this.ItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.Usuario[] List
        {
            get
            {
                return this.ListField;
            }
            set
            {
                this.ListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page
        {
            get
            {
                return this.PageField;
            }
            set
            {
                this.PageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Records
        {
            get
            {
                return this.RecordsField;
            }
            set
            {
                this.RecordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages
        {
            get
            {
                return this.TotalPagesField;
            }
            set
            {
                this.TotalPagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords
        {
            get
            {
                return this.TotalRecordsField;
            }
            set
            {
                this.TotalRecordsField = value;
            }
        }
    }
}
namespace CNPC.SISDUC.Model.Servicio
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OleoductoRequest", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model.Servicio")]
    public partial class OleoductoRequest : CNPC.SISDUC.Model.ObjectRequestOfOleoductorLr2Zji1
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OleoductoResponse", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model.Servicio")]
    public partial class OleoductoResponse : CNPC.SISDUC.Model.ResponseOfOleoductorLr2Zji1
    {
        
        private string MensajeErrorField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListRequestOfOleoductorLr2Zji1", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model.Servicio")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CNPC.SISDUC.Model.Servicio.OleoductoListaRequest))]
    public partial class ListRequestOfOleoductorLr2Zji1 : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CNPC.SISDUC.Model.Oleoducto[] ListaField;
        
        private CNPC.SISDUC.Model.Operacion OperacionField;
        
        private string TokenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.Oleoducto[] Lista
        {
            get
            {
                return this.ListaField;
            }
            set
            {
                this.ListaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.Operacion Operacion
        {
            get
            {
                return this.OperacionField;
            }
            set
            {
                this.OperacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OleoductoListaRequest", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model.Servicio")]
    public partial class OleoductoListaRequest : CNPC.SISDUC.Model.Servicio.ListRequestOfOleoductorLr2Zji1
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistroInspeccionVisualRequest", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model.Servicio")]
    public partial class RegistroInspeccionVisualRequest : CNPC.SISDUC.Model.ObjectRequestOfRegistroInspeccionVisualrLr2Zji1
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistroInspeccionVisualResponse", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model.Servicio")]
    public partial class RegistroInspeccionVisualResponse : CNPC.SISDUC.Model.ResponseOfRegistroInspeccionVisualrLr2Zji1
    {
        
        private string MensajeErrorField;
        
        private bool ResultadoField;
        
        private CNPC.SISDUC.Model.Oleoducto oleoductoField;
        
        private CNPC.SISDUC.Model.RegistroInspeccionVisual registroInspeccionVisualField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.Oleoducto oleoducto
        {
            get
            {
                return this.oleoductoField;
            }
            set
            {
                this.oleoductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CNPC.SISDUC.Model.RegistroInspeccionVisual registroInspeccionVisual
        {
            get
            {
                return this.registroInspeccionVisualField;
            }
            set
            {
                this.registroInspeccionVisualField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccesoriosRequest", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model.Servicio")]
    public partial class AccesoriosRequest : CNPC.SISDUC.Model.ObjectRequestOfAccesoriorLr2Zji1
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccesorioResponse", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model.Servicio")]
    public partial class AccesorioResponse : CNPC.SISDUC.Model.ResponseOfAccesoriorLr2Zji1
    {
        
        private string MensajeErrorField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioRequest", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model.Servicio")]
    public partial class UsuarioRequest : CNPC.SISDUC.Model.ObjectRequestOfUsuariorLr2Zji1
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioResponse", Namespace="http://schemas.datacontract.org/2004/07/CNPC.SISDUC.Model.Servicio")]
    public partial class UsuarioResponse : CNPC.SISDUC.Model.ResponseOfUsuariorLr2Zji1
    {
        
        private string MensajeErrorField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServicio")]
public interface IServicio
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/OleoductoEjecutarOperacion", ReplyAction="http://tempuri.org/IServicio/OleoductoEjecutarOperacionResponse")]
    CNPC.SISDUC.Model.Servicio.OleoductoResponse OleoductoEjecutarOperacion(CNPC.SISDUC.Model.Servicio.OleoductoRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/OleoductoEjecutarOperacion", ReplyAction="http://tempuri.org/IServicio/OleoductoEjecutarOperacionResponse")]
    System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.OleoductoResponse> OleoductoEjecutarOperacionAsync(CNPC.SISDUC.Model.Servicio.OleoductoRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/OleoductoEnviarActualizaciones", ReplyAction="http://tempuri.org/IServicio/OleoductoEnviarActualizacionesResponse")]
    CNPC.SISDUC.Model.Servicio.OleoductoResponse OleoductoEnviarActualizaciones(CNPC.SISDUC.Model.Servicio.OleoductoListaRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/OleoductoEnviarActualizaciones", ReplyAction="http://tempuri.org/IServicio/OleoductoEnviarActualizacionesResponse")]
    System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.OleoductoResponse> OleoductoEnviarActualizacionesAsync(CNPC.SISDUC.Model.Servicio.OleoductoListaRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/OleoductoListarAllEntidad", ReplyAction="http://tempuri.org/IServicio/OleoductoListarAllEntidadResponse")]
    CNPC.SISDUC.Model.Servicio.OleoductoResponse OleoductoListarAllEntidad();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/OleoductoListarAllEntidad", ReplyAction="http://tempuri.org/IServicio/OleoductoListarAllEntidadResponse")]
    System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.OleoductoResponse> OleoductoListarAllEntidadAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/OleoductoListarEntidad", ReplyAction="http://tempuri.org/IServicio/OleoductoListarEntidadResponse")]
    CNPC.SISDUC.Model.Servicio.OleoductoResponse OleoductoListarEntidad(string search, int page, int rowsPerPage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/OleoductoListarEntidad", ReplyAction="http://tempuri.org/IServicio/OleoductoListarEntidadResponse")]
    System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.OleoductoResponse> OleoductoListarEntidadAsync(string search, int page, int rowsPerPage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/RegistroInspeccionVisualEjecutarOperacion", ReplyAction="http://tempuri.org/IServicio/RegistroInspeccionVisualEjecutarOperacionResponse")]
    CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualResponse RegistroInspeccionVisualEjecutarOperacion(CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/RegistroInspeccionVisualEjecutarOperacion", ReplyAction="http://tempuri.org/IServicio/RegistroInspeccionVisualEjecutarOperacionResponse")]
    System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualResponse> RegistroInspeccionVisualEjecutarOperacionAsync(CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/RegistroInspeccionVisualListarAllEntidad", ReplyAction="http://tempuri.org/IServicio/RegistroInspeccionVisualListarAllEntidadResponse")]
    CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualResponse RegistroInspeccionVisualListarAllEntidad();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/RegistroInspeccionVisualListarAllEntidad", ReplyAction="http://tempuri.org/IServicio/RegistroInspeccionVisualListarAllEntidadResponse")]
    System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualResponse> RegistroInspeccionVisualListarAllEntidadAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/RegistroInspeccionVisualListarEntidad", ReplyAction="http://tempuri.org/IServicio/RegistroInspeccionVisualListarEntidadResponse")]
    CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualResponse RegistroInspeccionVisualListarEntidad(int oleoductoId, string search, int page, int rowsPerPage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/RegistroInspeccionVisualListarEntidad", ReplyAction="http://tempuri.org/IServicio/RegistroInspeccionVisualListarEntidadResponse")]
    System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualResponse> RegistroInspeccionVisualListarEntidadAsync(int oleoductoId, string search, int page, int rowsPerPage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AccesoriosEjecutarOperacion", ReplyAction="http://tempuri.org/IServicio/AccesoriosEjecutarOperacionResponse")]
    CNPC.SISDUC.Model.Servicio.AccesorioResponse AccesoriosEjecutarOperacion(CNPC.SISDUC.Model.Servicio.AccesoriosRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AccesoriosEjecutarOperacion", ReplyAction="http://tempuri.org/IServicio/AccesoriosEjecutarOperacionResponse")]
    System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.AccesorioResponse> AccesoriosEjecutarOperacionAsync(CNPC.SISDUC.Model.Servicio.AccesoriosRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AccesoriosListarAllEntidad", ReplyAction="http://tempuri.org/IServicio/AccesoriosListarAllEntidadResponse")]
    CNPC.SISDUC.Model.Servicio.AccesorioResponse AccesoriosListarAllEntidad();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AccesoriosListarAllEntidad", ReplyAction="http://tempuri.org/IServicio/AccesoriosListarAllEntidadResponse")]
    System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.AccesorioResponse> AccesoriosListarAllEntidadAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AccesoriosListarEntidad", ReplyAction="http://tempuri.org/IServicio/AccesoriosListarEntidadResponse")]
    CNPC.SISDUC.Model.Servicio.AccesorioResponse AccesoriosListarEntidad(int oleoductoId, string search, int page, int rowsPerPage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AccesoriosListarEntidad", ReplyAction="http://tempuri.org/IServicio/AccesoriosListarEntidadResponse")]
    System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.AccesorioResponse> AccesoriosListarEntidadAsync(int oleoductoId, string search, int page, int rowsPerPage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListCountUsuario", ReplyAction="http://tempuri.org/IServicio/ListCountUsuarioResponse")]
    ListCountUsuarioResponse ListCountUsuario(ListCountUsuarioRequest request);
    
    // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListCountUsuario", ReplyAction="http://tempuri.org/IServicio/ListCountUsuarioResponse")]
    System.Threading.Tasks.Task<ListCountUsuarioResponse> ListCountUsuarioAsync(ListCountUsuarioRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/UsuarioEjecutarOperacion", ReplyAction="http://tempuri.org/IServicio/UsuarioEjecutarOperacionResponse")]
    CNPC.SISDUC.Model.Servicio.UsuarioResponse UsuarioEjecutarOperacion(CNPC.SISDUC.Model.Servicio.UsuarioRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/UsuarioEjecutarOperacion", ReplyAction="http://tempuri.org/IServicio/UsuarioEjecutarOperacionResponse")]
    System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.UsuarioResponse> UsuarioEjecutarOperacionAsync(CNPC.SISDUC.Model.Servicio.UsuarioRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/UsuarioBuscarEntidad", ReplyAction="http://tempuri.org/IServicio/UsuarioBuscarEntidadResponse")]
    CNPC.SISDUC.Model.Servicio.UsuarioResponse UsuarioBuscarEntidad(CNPC.SISDUC.Model.Servicio.UsuarioRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/UsuarioBuscarEntidad", ReplyAction="http://tempuri.org/IServicio/UsuarioBuscarEntidadResponse")]
    System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.UsuarioResponse> UsuarioBuscarEntidadAsync(CNPC.SISDUC.Model.Servicio.UsuarioRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/UsuarioListarAllEntidad", ReplyAction="http://tempuri.org/IServicio/UsuarioListarAllEntidadResponse")]
    CNPC.SISDUC.Model.Servicio.UsuarioResponse UsuarioListarAllEntidad(string rowState);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/UsuarioListarAllEntidad", ReplyAction="http://tempuri.org/IServicio/UsuarioListarAllEntidadResponse")]
    System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.UsuarioResponse> UsuarioListarAllEntidadAsync(string rowState);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ValidaLogin", ReplyAction="http://tempuri.org/IServicio/ValidaLoginResponse")]
    CNPC.SISDUC.Model.Servicio.UsuarioResponse ValidaLogin(CNPC.SISDUC.Model.Servicio.UsuarioRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ValidaLogin", ReplyAction="http://tempuri.org/IServicio/ValidaLoginResponse")]
    System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.UsuarioResponse> ValidaLoginAsync(CNPC.SISDUC.Model.Servicio.UsuarioRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ValidaRolconAccion", ReplyAction="http://tempuri.org/IServicio/ValidaRolconAccionResponse")]
    bool ValidaRolconAccion(int rolid, string controller);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ValidaRolconAccion", ReplyAction="http://tempuri.org/IServicio/ValidaRolconAccionResponse")]
    System.Threading.Tasks.Task<bool> ValidaRolconAccionAsync(int rolid, string controller);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ListCountUsuario", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class ListCountUsuarioRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string error;
    
    public ListCountUsuarioRequest()
    {
    }
    
    public ListCountUsuarioRequest(string error)
    {
        this.error = error;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ListCountUsuarioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class ListCountUsuarioResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public int ListCountUsuarioResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public string error;
    
    public ListCountUsuarioResponse()
    {
    }
    
    public ListCountUsuarioResponse(int ListCountUsuarioResult, string error)
    {
        this.ListCountUsuarioResult = ListCountUsuarioResult;
        this.error = error;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServicioChannel : IServicio, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServicioClient : System.ServiceModel.ClientBase<IServicio>, IServicio
{
    
    public ServicioClient()
    {
    }
    
    public ServicioClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public CNPC.SISDUC.Model.Servicio.OleoductoResponse OleoductoEjecutarOperacion(CNPC.SISDUC.Model.Servicio.OleoductoRequest request)
    {
        return base.Channel.OleoductoEjecutarOperacion(request);
    }
    
    public System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.OleoductoResponse> OleoductoEjecutarOperacionAsync(CNPC.SISDUC.Model.Servicio.OleoductoRequest request)
    {
        return base.Channel.OleoductoEjecutarOperacionAsync(request);
    }
    
    public CNPC.SISDUC.Model.Servicio.OleoductoResponse OleoductoEnviarActualizaciones(CNPC.SISDUC.Model.Servicio.OleoductoListaRequest request)
    {
        return base.Channel.OleoductoEnviarActualizaciones(request);
    }
    
    public System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.OleoductoResponse> OleoductoEnviarActualizacionesAsync(CNPC.SISDUC.Model.Servicio.OleoductoListaRequest request)
    {
        return base.Channel.OleoductoEnviarActualizacionesAsync(request);
    }
    
    public CNPC.SISDUC.Model.Servicio.OleoductoResponse OleoductoListarAllEntidad()
    {
        return base.Channel.OleoductoListarAllEntidad();
    }
    
    public System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.OleoductoResponse> OleoductoListarAllEntidadAsync()
    {
        return base.Channel.OleoductoListarAllEntidadAsync();
    }
    
    public CNPC.SISDUC.Model.Servicio.OleoductoResponse OleoductoListarEntidad(string search, int page, int rowsPerPage)
    {
        return base.Channel.OleoductoListarEntidad(search, page, rowsPerPage);
    }
    
    public System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.OleoductoResponse> OleoductoListarEntidadAsync(string search, int page, int rowsPerPage)
    {
        return base.Channel.OleoductoListarEntidadAsync(search, page, rowsPerPage);
    }
    
    public CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualResponse RegistroInspeccionVisualEjecutarOperacion(CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualRequest request)
    {
        return base.Channel.RegistroInspeccionVisualEjecutarOperacion(request);
    }
    
    public System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualResponse> RegistroInspeccionVisualEjecutarOperacionAsync(CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualRequest request)
    {
        return base.Channel.RegistroInspeccionVisualEjecutarOperacionAsync(request);
    }
    
    public CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualResponse RegistroInspeccionVisualListarAllEntidad()
    {
        return base.Channel.RegistroInspeccionVisualListarAllEntidad();
    }
    
    public System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualResponse> RegistroInspeccionVisualListarAllEntidadAsync()
    {
        return base.Channel.RegistroInspeccionVisualListarAllEntidadAsync();
    }
    
    public CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualResponse RegistroInspeccionVisualListarEntidad(int oleoductoId, string search, int page, int rowsPerPage)
    {
        return base.Channel.RegistroInspeccionVisualListarEntidad(oleoductoId, search, page, rowsPerPage);
    }
    
    public System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.RegistroInspeccionVisualResponse> RegistroInspeccionVisualListarEntidadAsync(int oleoductoId, string search, int page, int rowsPerPage)
    {
        return base.Channel.RegistroInspeccionVisualListarEntidadAsync(oleoductoId, search, page, rowsPerPage);
    }
    
    public CNPC.SISDUC.Model.Servicio.AccesorioResponse AccesoriosEjecutarOperacion(CNPC.SISDUC.Model.Servicio.AccesoriosRequest request)
    {
        return base.Channel.AccesoriosEjecutarOperacion(request);
    }
    
    public System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.AccesorioResponse> AccesoriosEjecutarOperacionAsync(CNPC.SISDUC.Model.Servicio.AccesoriosRequest request)
    {
        return base.Channel.AccesoriosEjecutarOperacionAsync(request);
    }
    
    public CNPC.SISDUC.Model.Servicio.AccesorioResponse AccesoriosListarAllEntidad()
    {
        return base.Channel.AccesoriosListarAllEntidad();
    }
    
    public System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.AccesorioResponse> AccesoriosListarAllEntidadAsync()
    {
        return base.Channel.AccesoriosListarAllEntidadAsync();
    }
    
    public CNPC.SISDUC.Model.Servicio.AccesorioResponse AccesoriosListarEntidad(int oleoductoId, string search, int page, int rowsPerPage)
    {
        return base.Channel.AccesoriosListarEntidad(oleoductoId, search, page, rowsPerPage);
    }
    
    public System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.AccesorioResponse> AccesoriosListarEntidadAsync(int oleoductoId, string search, int page, int rowsPerPage)
    {
        return base.Channel.AccesoriosListarEntidadAsync(oleoductoId, search, page, rowsPerPage);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ListCountUsuarioResponse IServicio.ListCountUsuario(ListCountUsuarioRequest request)
    {
        return base.Channel.ListCountUsuario(request);
    }
    
    public int ListCountUsuario(ref string error)
    {
        ListCountUsuarioRequest inValue = new ListCountUsuarioRequest();
        inValue.error = error;
        ListCountUsuarioResponse retVal = ((IServicio)(this)).ListCountUsuario(inValue);
        error = retVal.error;
        return retVal.ListCountUsuarioResult;
    }
    
    public System.Threading.Tasks.Task<ListCountUsuarioResponse> ListCountUsuarioAsync(ListCountUsuarioRequest request)
    {
        return base.Channel.ListCountUsuarioAsync(request);
    }
    
    public CNPC.SISDUC.Model.Servicio.UsuarioResponse UsuarioEjecutarOperacion(CNPC.SISDUC.Model.Servicio.UsuarioRequest request)
    {
        return base.Channel.UsuarioEjecutarOperacion(request);
    }
    
    public System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.UsuarioResponse> UsuarioEjecutarOperacionAsync(CNPC.SISDUC.Model.Servicio.UsuarioRequest request)
    {
        return base.Channel.UsuarioEjecutarOperacionAsync(request);
    }
    
    public CNPC.SISDUC.Model.Servicio.UsuarioResponse UsuarioBuscarEntidad(CNPC.SISDUC.Model.Servicio.UsuarioRequest request)
    {
        return base.Channel.UsuarioBuscarEntidad(request);
    }
    
    public System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.UsuarioResponse> UsuarioBuscarEntidadAsync(CNPC.SISDUC.Model.Servicio.UsuarioRequest request)
    {
        return base.Channel.UsuarioBuscarEntidadAsync(request);
    }
    
    public CNPC.SISDUC.Model.Servicio.UsuarioResponse UsuarioListarAllEntidad(string rowState)
    {
        return base.Channel.UsuarioListarAllEntidad(rowState);
    }
    
    public System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.UsuarioResponse> UsuarioListarAllEntidadAsync(string rowState)
    {
        return base.Channel.UsuarioListarAllEntidadAsync(rowState);
    }
    
    public CNPC.SISDUC.Model.Servicio.UsuarioResponse ValidaLogin(CNPC.SISDUC.Model.Servicio.UsuarioRequest request)
    {
        return base.Channel.ValidaLogin(request);
    }
    
    public System.Threading.Tasks.Task<CNPC.SISDUC.Model.Servicio.UsuarioResponse> ValidaLoginAsync(CNPC.SISDUC.Model.Servicio.UsuarioRequest request)
    {
        return base.Channel.ValidaLoginAsync(request);
    }
    
    public bool ValidaRolconAccion(int rolid, string controller)
    {
        return base.Channel.ValidaRolconAccion(rolid, controller);
    }
    
    public System.Threading.Tasks.Task<bool> ValidaRolconAccionAsync(int rolid, string controller)
    {
        return base.Channel.ValidaRolconAccionAsync(rolid, controller);
    }
}
