//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPC.SISDUC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accesorio
    {
        public int Id { get; set; }
        public string NombreAccesorio { get; set; }
        public string CodigoTuberia { get; set; }
        public string Correlativo { get; set; }
        public string CodigoAccesorio { get; set; }
        public Nullable<decimal> NPS { get; set; }
        public Nullable<int> Schedule { get; set; }
        public string TipoMaterial { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public Nullable<int> CoordenadasUTMX { get; set; }
        public Nullable<int> CoordenadasUTMY { get; set; }
        public string Observaciones { get; set; }
        public string CondicionAccesorio { get; set; }
        public string RowState { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
