//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPC.SISDUC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ducto
    {
        public int Id { get; set; }
        public string Cliente { get; set; }
        public string Ducto1 { get; set; }
        public string NoLamina { get; set; }
        public string Trayectoria { get; set; }
        public string Ubicacion { get; set; }
        public string Inspector { get; set; }
        public Nullable<System.DateTime> FechaInspeccion { get; set; }
        public Nullable<int> NumeroTubos { get; set; }
        public Nullable<decimal> LongitudTotalTubo { get; set; }
        public Nullable<decimal> PresionDiseño { get; set; }
        public Nullable<decimal> PresionMaximaAdmisibleOperacion { get; set; }
        public Nullable<decimal> PresionMaximaOperacion { get; set; }
        public Nullable<decimal> PresionNormalOperacion { get; set; }
        public Nullable<decimal> TemperaturaMaximaOperacion { get; set; }
        public Nullable<decimal> TemperaturaNormalOperacion { get; set; }
        public Nullable<int> NPS { get; set; }
        public Nullable<decimal> Presion { get; set; }
        public Nullable<int> BLPD { get; set; }
        public Nullable<int> Shedule { get; set; }
        public string Material { get; set; }
        public Nullable<decimal> Temperatura { get; set; }
        public string BSW { get; set; }
        public Nullable<int> Esfuerzo_S { get; set; }
        public Nullable<int> FactorJunta_E { get; set; }
        public Nullable<decimal> FactorSensibilidadError { get; set; }
        public string RowState { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
