//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPC.SISDUC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oleoducto
    {
        public int Id { get; set; }
        public string Cliente { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string NoLamina { get; set; }
        public string Ubicacion { get; set; }
        public string Material1 { get; set; }
        public string Material2 { get; set; }
        public string Material3 { get; set; }
        public Nullable<int> Schedule1 { get; set; }
        public Nullable<int> Schedule2 { get; set; }
        public Nullable<int> Schedule3 { get; set; }
        public Nullable<int> BLPD { get; set; }
        public Nullable<decimal> Presion { get; set; }
        public Nullable<decimal> Temperatura { get; set; }
        public string BSW { get; set; }
        public Nullable<System.DateTime> FechaInspeccion { get; set; }
        public string RowState { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
